// Generated by scripts/assets/falcon-screens.mjs. Do not edit by hand.
/** [width, height] in pixels of the bundled Falcon ERP screens (public/images/v2/screen-*.png). */
export const SCREEN_SIZES: Record<string, readonly [number, number]> = {
  "/images/v2/screen-dashboard.png": [1280, 677],
  "/images/v2/screen-trial-balance.png": [1280, 677],
};
